WebContent/src/com/neos/marketing/bean/NoteBean.java
package com.neos.marketing.bean;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;

import javax.faces.event.*;
import javax.faces.model.SelectItem;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import com.neos.marketing.bo.*;
import com.neos.marketing.facade.*;
import com.neos.marketing.manage.*;
import com.neos.marketing.list.*;
import com.neos.marketing.util.MessageBean;
import com.neos.marketing.util.JSFUtil;

public class NoteBean implements java.io.Serializable {

	private Long noteId  = null;
	private String objectType  = null;
	private Long objectId  = null;
	private String note  = null;
	private int pageNum = 0;
	private int maxRows = 15;
	private boolean isLastPage = false;
	private boolean isFirstPage = true;
	private boolean selected = false;
	
	public NoteBean(){}
	
	public NoteBean(NoteBO theBO){
		this.mapToBO(theBO);
	}
	
	public void mapToBO(NoteBO theBO){
		this.noteId = theBO.getNoteId();  
		this.objectType = theBO.getObjectType();  
		this.objectId = theBO.getObjectId();  
		this.note = theBO.getNote();  
	}


	public String deleteAction(){
		ArrayList results = ((NoteList)JSFUtil.getSessionBean("NoteList")).getNoteList();
		if(results.size() <= 1){
	    	this.pageNum--;
	    }
		NoteActionManager manager = new NoteActionManager();
		String returnStr = manager.deleteAction();
		if(returnStr.equalsIgnoreCase("success")){
			return manager.listNavigate(maxRows, pageNum);
		}else{
			return returnStr;
		}
	}
	
	public String createAction(){
		NoteActionManager manager = new NoteActionManager();
		NoteBO createBO = new NoteBO();
		createBO.setNoteId(noteId);
		createBO.setObjectType(objectType);
		createBO.setObjectId(objectId);
		createBO.setNote(note);
		String returnStr = manager.createAction(createBO);
		if(returnStr.equalsIgnoreCase("success")){
			return manager.listNavigate(maxRows, pageNum);
		}else{
			return returnStr;
		}
	}
	
	/* function to create Note called in other beans */
	public void createNoteAction(String createNoteType, Long createObjectId, String createNote){
		NoteActionManager manager = new NoteActionManager();
		NoteBO createBO = new NoteBO();
		this.noteId = null;
		createBO.setNoteId(noteId);
		createBO.setObjectType(createNoteType);
		createBO.setObjectId(createObjectId);
		createBO.setNote(createNote);
		manager.createAction(createBO);
	}
	
	public String editAction(){
		NoteActionManager manager = new NoteActionManager();
		NoteBO editBO = new NoteBO();
		editBO.setNoteId(noteId);
		editBO.setObjectType(objectType);
		editBO.setObjectId(objectId);
		editBO.setNote(note);
		NoteBO pkBO = new NoteBO();
		pkBO.setNoteId(this.getNoteId());
		String returnStr = manager.editAction(editBO, pkBO);
		if(returnStr.equalsIgnoreCase("success")){
			return manager.listNavigate(maxRows, pageNum);
		}else{
			return returnStr;
		}
	}
	
	public String searchAction(){
		NoteActionManager manager = new NoteActionManager();
		NoteBO searchBO = new NoteBO();

		if(noteId!=null){		
			searchBO.setNoteId(noteId);
		}

		if(objectType!=null){		
			searchBO.setObjectType(objectType);
		}

		if(objectId!=null){		
			searchBO.setObjectId(objectId);
		}

		if(note!=null){		
			searchBO.setNote(note);
		}
		JSFUtil.addToSession("NoteSearchBO", searchBO);
		return this.listNavigate();
	}
	
	public String clearSearchAction(){
		JSFUtil.removeFromSession("NoteSearchBO");
		noteId=null;
		objectType=null;
		objectId=null;
		note=null;
		return this.listNavigate();
	}
	
	public String deleteNavigate(){
		NoteActionManager manager = new NoteActionManager();
		return manager.deleteNavigate();
	}
	
	/* Function called from another object's edit page to delete specified note*/
	public void deleteNoteAction(){
		NoteActionManager manager = new NoteActionManager();
		manager.deleteNoteAction(noteId, objectType, objectId, note);
	}

	private void populateDetailLists() {
	}
	
	public String createNavigate(){
		NoteActionManager manager = new NoteActionManager();
		clearBean();
		String action = null;
		action = manager.createNavigate();
		populateDetailLists();    		
		return action;
	}
		
	public String editNavigate(){
		NoteActionManager manager = new NoteActionManager();
		String action = manager.editNavigate();
		populateDetailLists();
		return action;
	}
	
	/* Function called from another object's edit page to delete specified note*/
	public void editNoteAction(){
		NoteActionManager manager = new NoteActionManager();
		manager.editNoteAction(noteId, objectType, objectId, note);
	}
	
	public String listNavigate(){
		NoteActionManager manager = new NoteActionManager();
		String theReturn = manager.listNavigate(maxRows, pageNum);
		populateDetailLists();
		checkFirstLastPage();
		return theReturn;
	}

	/* Populates the notes List with the object type and objectId */
	public void populateFilter(String objectType, Long objectId){
		NoteActionManager manager = new NoteActionManager();
		manager.populateFilter(objectType, objectId);
		return;
	}
	
	
	public String searchNavigate(){
		NoteActionManager manager = new NoteActionManager();
		String action = manager.searchNavigate();
		clearBean();
		return action;	
	}
	
	public Collection getResults(){
		NoteActionManager manager = new NoteActionManager();
		return manager.getResults();
	}
	
	public void setResults(ArrayList results){
		NoteActionManager manager = new NoteActionManager();
		manager.setResults(results);
	}
	
	public void selected(){
		NoteActionManager manager = new NoteActionManager();
	    NoteBean selBean = new NoteBean();
		selBean.setNoteId(noteId);
		selBean.setObjectType(objectType);
		selBean.setObjectId(objectId);
		selBean.setNote(note);
		ArrayList results = ((NoteList)JSFUtil.getSessionBean("NoteList")).getNoteList();
     	for (Iterator i = results.iterator(); i.hasNext();) {
     		NoteBean temp = (NoteBean) i.next();
     		if(temp.isSelected()) {
     			// Ensures only one is selected at a time
     			temp.setSelected(false);
     			((NoteList)JSFUtil.getSessionBean("NoteList")).setEditDisabled(true);
     		} else if(temp.equals(selBean)){
     			temp.setSelected(!temp.isSelected());
     			if(temp.isSelected() == true){
     				((NoteList)JSFUtil.getSessionBean("NoteList")).setEditDisabled(false);
     			}
     			else{
     				((NoteList)JSFUtil.getSessionBean("NoteList")).setEditDisabled(true);
     			}
     		} 
     	}
	}
	
	public void prevResults(){
		NoteActionManager manager = new NoteActionManager();
    	pageNum--;
		manager.listNavigate(maxRows, pageNum);
		checkFirstLastPage();
	}
	
	public void nextResults(){
		NoteActionManager manager = new NoteActionManager();
    	pageNum++;
		manager.listNavigate(maxRows, pageNum);
		checkFirstLastPage();
	}
	
	public void checkFirstLastPage(){
		NoteList list = (NoteList)JSFUtil.getSessionBean("NoteList");
		int listSize = list.getNoteList().size();
		int startingPoint = maxRows * pageNum;
        if(pageNum == 0){
     		this.setFirstPage(true);
     	}else{
     		this.setFirstPage(false);
     	}
		if(listSize < maxRows ||
     			(listSize == maxRows &&
     					startingPoint + listSize == list.getTotalSize())){
     		this.setLastPage(true);
     	}else{
     		this.setLastPage(false);
     	}
    }	

	private void clearBean(){
		NoteActionManager manager = new NoteActionManager();
		this.noteId  = null;
		this.objectType  = null;
		this.objectId  = null;
		this.note  = null;
	}


	/**
	 * get the NoteId attribute
	 * @return the value of the NoteId attribute
	 */	
	public Long getNoteId() {
    	return this.noteId;
   	}

	/**
	 * set the NoteId attribute to a value defined by a Long
	 * @param noteId the long value for the attribute
	 */
	public void setNoteId(Long noteId) {
    	this.noteId = noteId;
	}
	/**
	 * overloaded method to set the NoteId attribute to a value defined by a |Long|
	 * @param noteId the String value for the attribute
	 */
	public void setNoteId(String noteId) {
    	this.noteId = new Long(noteId);
	}

	/**
	 * get the ObjectType attribute
	 * @return the value of the ObjectType attribute
	 */	
	public String getObjectType() {
    	return this.objectType;
   	}

	/**
	 * set the ObjectType attribute to a value defined by a String
	 * @param objectType the long value for the attribute
	 */
	public void setObjectType(String objectType) {
    	this.objectType = objectType;
	}

	/**
	 * get the ObjectId attribute
	 * @return the value of the ObjectId attribute
	 */	
	public Long getObjectId() {
    	return this.objectId;
   	}

	/**
	 * set the ObjectId attribute to a value defined by a Long
	 * @param objectId the long value for the attribute
	 */
	public void setObjectId(Long objectId) {
    	this.objectId = objectId;
	}
	/**
	 * overloaded method to set the ObjectId attribute to a value defined by a |Long|
	 * @param objectId the String value for the attribute
	 */
	public void setObjectId(String objectId) {
    	this.objectId = new Long(objectId);
	}

	/**
	 * get the Note attribute
	 * @return the value of the Note attribute
	 */	
	public String getNote() {
    	return this.note;
   	}

	/**
	 * set the Note attribute to a value defined by a String
	 * @param note the long value for the attribute
	 */
	public void setNote(String note) {
    	this.note = note;
	}



	public int getMaxRows() {
		return maxRows;
	}

	public void setMaxRows(int maxRows) {
		this.maxRows = maxRows;
	}

	public int getPageNum() {
		return pageNum;
	}

	public void setPageNum(int pageNum) {
		this.pageNum = pageNum;
	}

	public boolean isSelected() {
		return selected;
	}

	public void setSelected(boolean selected) {
		this.selected = selected;
	}
	
	public boolean isFirstPage() {
		return isFirstPage;
	}

	public void setFirstPage(boolean isFirstPage) {
		this.isFirstPage = isFirstPage;
	}

	public boolean isLastPage() {
		return isLastPage;
	}

	public void setLastPage(boolean isLastPage) {
		this.isLastPage = isLastPage;
	}
    
    public boolean equals(NoteBean temp){

WebContent/src/com/neos/marketing/dto/CompanyDTO.java
package com.neos.marketing.dto;

/**
 * Container for .Company data.
 * <pre>
 * Copyright: 2015
 * Company: NEOS
 * </pre>
 * @author Vgo
 * @version 1.2
 */
public class CompanyDTO implements java.io.Serializable {

	private Long companyId  = null;  
	private String name  = null;  


	/**
	 * a simple constructor
	 */
	public CompanyDTO() {
	}

	
	/**
	 * get the CompanyId attribute
	 * @return the value of the CompanyId attribute
	 */	
	public Long getCompanyId() {
    	return this.companyId;
   	}

	/**
	 * set the CompanyId attribute to a value defined by a Long
	 * @param companyId the long value for the attribute
	 */
	public void setCompanyId(Long companyId) {
    	this.companyId = companyId;
	}
	/**
	 * overloaded method to set the CompanyId attribute to a value defined by a |Long|
	 * @param companyId the String value for the attribute
	 */
	public void setCompanyId(String companyId) {
    	this.companyId = new Long(companyId);
	}
	/**
	 * get the Name attribute
	 * @return the value of the Name attribute
	 */	
	public String getName() {
    	return this.name;
   	}

	/**
	 * set the Name attribute to a value defined by a String
	 * @param name the long value for the attribute
	 */
	public void setName(String name) {
    	this.name = name;
	}

	/**
	 * returns a DTO object that is just the PrimaryKey values of this DTO
	 * @return a CompanyDTO with only the Primary Key Values set
	 */ 	
   public CompanyDTO getPKDTO() {
		CompanyDTO pkDTO = new CompanyDTO();
		pkDTO.setCompanyId(this.getCompanyId());
		return(pkDTO);
	}// end getPKDTO

	/**
	 * returns a String that is a description of an instance of this CompanyDTO object.  This is
	 * used in all list displays and should be overwritten to change those views.
	 * @return a String that is a description of an instance of this CompanyDTO object.
	 */   
	public String getTableDescription() {
      //Use for debugging and logging
      StringBuffer description = new StringBuffer("");
      return description.toString();
   }

}

WebContent/src/com/neos/marketing/dto/DetailDTO.java
package com.neos.marketing.dto;

/**
 * Container for .Detail data.
 * <pre>
 * Copyright: 2015
 * Company: NEOS
 * </pre>
 * @author Vgo
 * @version 1.2
 */
public class DetailDTO implements java.io.Serializable {

	private Long detailId  = null;  
	private Long sourceId  = null;  
	private String detail  = null;  


	/**
	 * a simple constructor
	 */
	public DetailDTO() {
	}

	
	/**
	 * get the DetailId attribute
	 * @return the value of the DetailId attribute
	 */	
	public Long getDetailId() {
    	return this.detailId;
   	}

	/**
	 * set the DetailId attribute to a value defined by a Long
	 * @param detailId the long value for the attribute
	 */
	public void setDetailId(Long detailId) {
    	this.detailId = detailId;
	}
	/**
	 * overloaded method to set the DetailId attribute to a value defined by a |Long|
	 * @param detailId the String value for the attribute
	 */
	public void setDetailId(String detailId) {
    	this.detailId = new Long(detailId);
	}
	/**
	 * get the SourceId attribute
	 * @return the value of the SourceId attribute
	 */	
	public Long getSourceId() {
    	return this.sourceId;
   	}

	/**
	 * set the SourceId attribute to a value defined by a Long
	 * @param sourceId the long value for the attribute
	 */
	public void setSourceId(Long sourceId) {
    	this.sourceId = sourceId;
	}
	/**
	 * overloaded method to set the SourceId attribute to a value defined by a |Long|
	 * @param sourceId the String value for the attribute
	 */
	public void setSourceId(String sourceId) {
    	this.sourceId = new Long(sourceId);
	}
	/**
	 * get the Detail attribute
	 * @return the value of the Detail attribute
	 */	
	public String getDetail() {
    	return this.detail;
   	}

	/**
	 * set the Detail attribute to a value defined by a String
	 * @param detail the long value for the attribute
	 */
	public void setDetail(String detail) {
    	this.detail = detail;
	}

	/**
	 * returns a DTO object that is just the PrimaryKey values of this DTO
	 * @return a DetailDTO with only the Primary Key Values set
	 */ 	
   public DetailDTO getPKDTO() {
		DetailDTO pkDTO = new DetailDTO();
		pkDTO.setDetailId(this.getDetailId());
		return(pkDTO);
	}// end getPKDTO

	/**
	 * returns a String that is a description of an instance of this DetailDTO object.  This is
	 * used in all list displays and should be overwritten to change those views.
	 * @return a String that is a description of an instance of this DetailDTO object.
	 */   
	public String getTableDescription() {
      //Use for debugging and logging
      StringBuffer description = new StringBuffer("");
      return description.toString();
   }

}

WebContent/src/com/neos/marketing/dto/EmailDTO.java
package com.neos.marketing.dto;

/**
 * Container for .Email data.
 * <pre>
 * Copyright: 2015
 * Company: NEOS
 * </pre>
 * @author Vgo
 * @version 1.2
 */
public class EmailDTO implements java.io.Serializable {

	private Long emailId  = null;  
	private String emailAddress  = null;  
	private Long personId  = null;  


	/**
	 * a simple constructor
	 */
	public EmailDTO() {
	}

	
	/**
	 * get the EmailId attribute
	 * @return the value of the EmailId attribute
	 */	
	public Long getEmailId() {
    	return this.emailId;
   	}

	/**
	 * set the EmailId attribute to a value defined by a Long
	 * @param emailId the long value for the attribute
	 */
	public void setEmailId(Long emailId) {
    	this.emailId = emailId;
	}
	/**
	 * overloaded method to set the EmailId attribute to a value defined by a |Long|
	 * @param emailId the String value for the attribute
	 */
	public void setEmailId(String emailId) {
    	this.emailId = new Long(emailId);
	}
	/**
	 * get the EmailAddress attribute
	 * @return the value of the EmailAddress attribute
	 */	
	public String getEmailAddress() {
    	return this.emailAddress;
   	}

	/**
	 * set the EmailAddress attribute to a value defined by a String
	 * @param emailAddress the long value for the attribute
	 */
	public void setEmailAddress(String emailAddress) {
    	this.emailAddress = emailAddress;
	}
	/**
	 * get the PersonId attribute
	 * @return the value of the PersonId attribute
	 */	
	public Long getPersonId() {
    	return this.personId;
   	}

	/**
	 * set the PersonId attribute to a value defined by a Long
	 * @param personId the long value for the attribute
	 */
	public void setPersonId(Long personId) {
    	this.personId = personId;
	}
	/**
	 * overloaded method to set the PersonId attribute to a value defined by a |Long|
	 * @param personId the String value for the attribute
	 */
	public void setPersonId(String personId) {
    	this.personId = new Long(personId);
	}

	/**
	 * returns a DTO object that is just the PrimaryKey values of this DTO
	 * @return a EmailDTO with only the Primary Key Values set
	 */ 	
   public EmailDTO getPKDTO() {
		EmailDTO pkDTO = new EmailDTO();
		pkDTO.setEmailId(this.getEmailId());
		return(pkDTO);
	}// end getPKDTO

	/**
	 * returns a String that is a description of an instance of this EmailDTO object.  This is
	 * used in all list displays and should be overwritten to change those views.
	 * @return a String that is a description of an instance of this EmailDTO object.
	 */   
	public String getTableDescription() {
      //Use for debugging and logging
      StringBuffer description = new StringBuffer("");
      return description.toString();
   }

}

WebContent/pages/CompanyList.xhtml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html" 
    xmlns:c="http://java.sun.com/jstl/core"
    xmlns:ui="http://java.sun.com/jsf/facelets">
	
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=Cp1252"/>
	<title>Company Table List</title>
	<link href="../css/style.css" rel="stylesheet" type="text/css" />
	<link href="../css/layout.css" rel="stylesheet" type="text/css" />
</head>
<body>
	<div id="wrapper">
	   	<div id="header">
	   		<h2 style="float:left">Marketing Database</h2>
	   		<div style="clear:both"></div>
		</div>
		<div id="content">
<h:form id="form1">			
			<f:view>
				<!-- Menu -->
				<div id="left">
				    <div class="sectionHeader">Menu</div>
				    <ui:include src="menu.xhtml"/>
				</div>						
				<div id="right">
					
				
						<div class="sectionHeader">
							<div style="position: relative; left: 5px;">
								<p style="float:left">	
									<b>Company</b><h:outputText value="&#160;" /><h:outputText value="&#160;" /><h:outputText value="&#160;" /><h:outputText value="&#160;" /><h:outputText value="&#160;" />
								</p>

								<h:commandButton value="Clear Search" style="float:right" action="#{CompanyBean.clearSearchAction}" />
								<h:commandButton value="Search" style="float:right" action="#{CompanyBean.searchNavigate}" />
								<h:commandButton value="Delete" style="float:right" action="#{CompanyBean.deleteAction}" onclick="return confirm('Are you sure you want to delete?')" />
								<h:commandButton value="Create" style="float:right" action="#{CompanyBean.createNavigate}" />
								<h:commandButton disabled="#{CompanyList.editDisabled}" value="Edit" style="float:right" action="#{CompanyBean.editNavigate}" />
								<h:commandButton disabled="true" style="float:right" value="List" action="#{CompanyBean.listNavigate}" />
								<h:commandButton style="float:right" value="Export to CSV" action="#{CompanyBean.exporttoCSV}" />

								<div style="clear:both"></div>
							</div>
						</div>
	
						<h:dataTable value="#{CompanyList.companyList}" var="rows" preserveDataModel="true" styleClass="livetableList" columnClasses="blank,  companyName">								
							
							<h:column headerClass="blank">
								<f:facet name="header">
									Select
								</f:facet>
								<h:commandLink action="#{CompanyBean.selected}" rendered="#{rows.selected}">
									
									 	<div id="radio" class="radio_check"></div>
									 	
									<f:setPropertyActionListener target="#{CompanyBean.companyId}" value="#{rows.companyId}" />
									<f:setPropertyActionListener target="#{CompanyBean.name}" value="#{rows.name}" />
									<f:setPropertyActionListener target="#{CompanyBean.entityCompanyFkList}" value="#{rows.entityCompanyFkList}" />
									<f:setPropertyActionListener target="#{CompanyBean.companyFkList}" value="#{rows.companyFkList}" />
								</h:commandLink>
								<h:commandLink action="#{CompanyBean.selected}" rendered="#{not rows.selected}">
									
									 	<div id="radio" class="radio_uncheck"></div>
									
									<f:setPropertyActionListener target="#{CompanyBean.companyId}" value="#{rows.companyId}" />
									<f:setPropertyActionListener target="#{CompanyBean.name}" value="#{rows.name}" />
									<f:setPropertyActionListener target="#{CompanyBean.entityCompanyFkList}" value="#{rows.entityCompanyFkList}" />
									<f:setPropertyActionListener target="#{CompanyBean.companyFkList}" value="#{rows.companyFkList}" />
								</h:commandLink>
							</h:column>
							<h:column headerClass="companyName">
								<f:facet name="header">
									<div class="name">Name</div>
								</f:facet>
								<h:outputText value="#{rows.name}" styleClass="name" />
							</h:column>
						</h:dataTable>

						<div class="listNav">

							<h:commandLink id="prevBtn" action="#{CompanyBean.prevResults}" rendered="#{!CompanyBean.firstPage}" styleClass="prevLink">
								<h:outputText value="&lt;&lt; Prev"/>
							</h:commandLink>	
							<h:commandLink id="nextBtn" action="#{CompanyBean.nextResults}" rendered="#{!CompanyBean.lastPage}" styleClass="nextLink">
								<h:outputText value="Next &gt;&gt;"/>
							</h:commandLink>								

						</div>

						<h:outputText value="#{MessageBean.msg}" styleClass="error"/>
					
				</div> <!-- right -->
			</f:view>
					<div id="footer" >
			<div style="border-top:1px solid #999;">
				<div style="margin-right:auto; margin-left:auto; width: 850px;">
					<div style="float:left; width: 90px;"><a href="http://www.vgosoftware.com"><img src="../images/arrow.gif"/></a></div>
					<div style="float:left; padding-top: 15px;">Footer Text, Maybe some various copyright stuff.	Vgo Software 2007. Maybe some disclaimers. Rev does not cure hangovers.</div>
					<div style="float:left; width: 90px;"><a href="http://www.vgosoftware.com"><img src="../images/text.gif" /></a></div>
					<br style="clear: both" />
				</div>
			</div>
		</div> <!-- Footer -->
		</h:form>
	</div> <!-- content -->
	</div> <!-- wrapper -->
</body>
</html>

WebContent/pages/DetailSearch.xhtml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html" 
	xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:c="http://java.sun.com/jstl/core">
	
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=Cp1252"/>
	<title>Detail Table List</title>
	<link href="../css/style.css" rel="stylesheet" type="text/css" />
	<link href="../css/layout.css" rel="stylesheet" type="text/css" />
</head>
<body>
	<div id="wrapper">
	   	<div id="header">
	   		<h2 style="float:left">Marketing Database</h2>
	   		<div style="clear:both"></div>
		</div>	
		<div id="content">
		<h:form id="form1">	
			<f:view>
				<!-- Menu -->
				<div id="left">
				    <div class="sectionHeader">Menu</div>
				    <ui:include src="menu.xhtml"/>
				</div>				
				<div id="right">				
					

						<div class="sectionHeader">
							<div style="position: relative; left: 5px;">
								<p style="float:left">
									<b>Detail</b><h:outputText value="&#160;" /><h:outputText value="&#160;" />
									<h:outputText value="&#160;" /><h:outputText value="&#160;" /><h:outputText value="&#160;" />
								</p>

								<h:commandButton value="Clear Search" style="float:right" action="#{DetailBean.clearSearchAction}" />								
								<h:commandButton disabled="true" style="float:right" value="Search" action="#{DetailBean.searchNavigate}" />
								<h:commandButton disabled="true" style="float:right" value="Delete" action="#{DetailBean.deleteAction}" />
								<h:commandButton value="Create" style="float:right" action="#{DetailBean.createNavigate}" />
								<h:commandButton disabled="true" style="float:right" value="Edit" action="#{DetailBean.editNavigate}" />
								<h:commandButton value="List" style="float:right" action="#{DetailBean.listNavigate}" />

								<div style="clear:both;"></div>
							</div>
						</div>				
						<div id="contentHeader"><br/>Enter Search Criteria<br/><br/></div>	
						<div id="searchFields">
							<div class="contentLabel">
								Source:
							</div>
							<div class="contentField">

								<h:selectOneMenu value="#{DetailBean.sourceId}" valueChangeListener="#{DetailBean.setSourceId}" styleClass="dropBox">
									<f:selectItems value="#{DetailBean.sourceIdResults}"/>
								</h:selectOneMenu>

							</div>


							<div class="contentLabel">
								Detail:
							</div>
							<div class="contentField">

								<h:inputText value='#{DetailBean.detail}' styleClass="detail"/>

							</div>


							<div style="clear:both"></div>
						</div> <!-- search fields -->
						<div id="contentButtons">

							<h:commandButton value="Cancel" style="float:right" action="#{DetailBean.listNavigate}" />
							<h:commandButton value="All Records" style="float:right" action="#{DetailBean.clearSearchAction}" />
							<h:commandButton value="Search" style="float:right" action="#{DetailBean.searchAction}" />

							<div style="clear:both"></div>
						</div>

						<h:outputText value="#{MessageBean.msg}" styleClass="error"/>				
					
				</div> <!-- right -->					
			</f:view>
					<div id="footer" >
			<div style="border-top:1px solid #999;">
				<div style="margin-right:auto; margin-left:auto; width: 850px;">
					<div style="float:left; width: 90px;"><a href="http://www.vgosoftware.com"><img src="../images/arrow.gif"/></a></div>
					<div style="float:left; padding-top: 15px;">Footer Text, Maybe some various copyright stuff.	Vgo Software 2007. Maybe some disclaimers. Rev does not cure hangovers.</div>
					<div style="float:left; width: 90px;"><a href="http://www.vgosoftware.com"><img src="../images/text.gif"/></a></div>
					<br style="clear: both" />
				</div>
			</div>
		</div> <!-- Footer -->
		</h:form>
	</div><!-- content -->
	</div><!-- wrapper -->
</body>
</html>